### PR TITLE
Update zh_TW translations.

### PR DESCRIPTION
**Pull request by s8321414**
I updated zh_TW translations, please review and merge it :smiley:

### CODE REVIEW

**Comment by s8321414** [comment]
Ah OK, I already request zh_TW there, and I will closr this PR.

**Comment by schomery** [comment]
thanks. let me know when the translation is ready.

**Comment by schomery** [comment]
> And could you sync GitHub and Transifex

done. If you are not comfortable with "transifex" you can request a new pull merge. Being in "transifex" only helps getting the updating notifications

**Comment by s8321414** [comment]
Thank you! :smiley:

**Comment by s8321414** [comment]
It seems I also need webstore.txt synced...

**Comment by schomery** [comment]
I tried, but I got a message that strings do not match. Can you copy and paste each string in the online editor https://www.transifex.com/github-7/privacy-settings/viewstrings/#zh_TW/webstoretxt_1/126014016

**Comment by s8321414** [comment]
Done, thank you :smiley:

**Pull request closed without merging**
