### PR TITLE
Update es.properties

### PR DESCRIPTION
**Pull request by franco999**

### CODE REVIEW

**Comment by schomery** [comment]
Thanks for the update

**Comment by schomery** [comment]
Hi, would you please push a new update

**Comment by franco999** [comment]
Please, add in es.properties the strings to translate to know what are.
Do you plan to use online tools like Weblate or Crowdin?

**Comment by schomery** [comment]
I am not really familiar with these services. Please add the project to one that you think is easier to use and I'll push updates into it.

**Pull request merged**
